server:
  servlet:
    context-path: /rest/v2

spring:
  datasource:
    url: jdbc:postgresql://192.168.137.100:5432/swr2
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  security:
    user:
      name: kretsev_a
      password: C3y5KjZhsrqtuSr4